# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Wasm CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build wasm
        run: wasm-pack build --target web --out-dir si-web-react/src/si-emu-pkg --release
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: si-web-react/package-lock.json
      - run: npm install
        working-directory: ./si-web-react
      - run: npm run build --if-present
        working-directory: ./si-web-react
#      - run: npm test
#        working-directory: ./si-web-react
