name: Rust Publish

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-windows:
    name: Build windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile code
        run: cargo build --release
      - name: Copy exe to root
        run: cp ./target/release/space_invaders_arcade_emulator.exe .
      - name: Copy dll to root
        run: cp ./msvc/dll/64/SDL2.dll .
      - name: Upload artifact release
        uses: actions/upload-artifact@v2
        with:
          name: artifact-windows
          path: |
            ./space_invaders_arcade_emulator.exe
            ./SDL2.dll
            ./SDL2_mixer.dll
            ./game_roms
  build-ubuntu:
    name: Build ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download libraries
        run: sudo apt-get install libsdl2-dev libsdl2-mixer-dev
      - name: Compile code
        run: cargo build --release
      - name: Copy exe to root
        run: cp ./target/release/space_invaders_arcade_emulator .
      - name: Upload artifact release
        uses: actions/upload-artifact@v2
        with:
          name: artifact-ubuntu
          path: |
            ./space_invaders_arcade_emulator
            ./game_roms
  build-macos:
    name: Build macos
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download libraries
        run: |
          brew install sdl2
          brew install sdl2_mixer
      - name: Add lib to path
        run: export LIBRARY_PATH="$LIBRARY_PATH:/opt/local/lib/"
      - name: Compile code
        run: cargo build --release
      - name: Copy exe to root
        run: cp ./target/release/space_invaders_arcade_emulator .
      - name: Upload artifact release
        uses: actions/upload-artifact@v2
        with:
          name: artifact-macos
          path: |
            ./space_invaders_arcade_emulator
            ./game_roms
  release-project:
    name: Release project
    runs-on: ubuntu-latest
    needs: [ build-windows, build-ubuntu, build-macos ]
    steps:
      - name: Download windows artifact content
        uses: actions/download-artifact@v2
        with:
          name: artifact-windows
      - name: View content
        run: ls -R
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - name: Archive windows release
        uses: thedoctor0/zip-release@master
        with:
          filename: release-windows.zip
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: release-windows.zip
          asset_name: space_invaders_arcade_emulator-windows-v${{ github.run_number }}.zip
          asset_content_type: application/zip
      - name: Delete windows release files
        run: |
          rm space_invaders_arcade_emulator.exe
          rm release-windows.zip
          rm SDL2.dll
          rm SDL2_mixer.dll
      - name: Download ubuntu artifact content
        uses: actions/download-artifact@v2
        with:
          name: artifact-ubuntu
      - name: View content
        run: ls -R
      - name: Archive ubuntu release
        uses: thedoctor0/zip-release@master
        with:
          filename: release-linux.tar.gz
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: release-linux.tar.gz
          asset_name: space_invaders_arcade_emulator-linux-v${{ github.run_number }}.tar.gz
          asset_content_type: application/zip
      - name: Delete ubuntu release files
        run: |
          rm space_invaders_arcade_emulator
          rm release-linux.tar.gz
      - name: Download macos artifact content
        uses: actions/download-artifact@v2
        with:
          name: artifact-macos
      - name: View content
        run: ls -R
      - name: Archive macos release
        uses: thedoctor0/zip-release@master
        with:
          filename: release-macos.tar.gz
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: release-macos.tar.gz
          asset_name: space_invaders_arcade_emulator-macos-v${{ github.run_number }}.tar.gz
          asset_content_type: application/zip
