name: rust-publish

# thanks to:
# https://github.com/msusdev/end-to-end-github-actions/blob/main/presentations/ci_github_actions.md
# https://www.youtube.com/watch?v=cvvOqNorlZQ
# other
# https://github.com/marketplace/actions/create-release
# https://github.com/marvinpinto/action-automatic-releases
# https://alexene.dev/2019/09/04/Github-actions-CI-rust-SDL2.html

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-project:
    name: Build project
    runs-on: windows-2016
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile code
        run: cargo build --release
      - name: Upload artifact release
        uses: actions/upload-artifact@v2
        with:
          name: artifact-release
          path: ./target/release/space_invaders_arcade_emulator.exe
  release-project:
    name: Release project
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download artifact content
        uses: actions/download-artifact@v2
        with:
          name: artifact-release
      - name: View content
        run: ls -R
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - name: Archive release
        uses: thedoctor0/zip-release@master
        with:
          filename: release-windows.zip
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: release-windows.zip
          asset_name: space_invaders_arcade_emulator-v${{ github.run_number }}.zip
          asset_content_type: application/zip
