name: Wasm NPM Publish

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install wasm-pack
        run: |
          cargo install wasm-pack
          export PATH="$HOME/.cargo/bin:$PATH"

      - name: Build wasm
        run: wasm-pack build --target web --out-name index --out-dir si-emu-pkg --release

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          cd si-emu-pkg
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}