name: Wasm build

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download libraries
        run: sudo apt-get install libsdl2-dev libsdl2-mixer-dev
      - name: Build wasm
        run: wasm-pack build --target web --out-dir web/pkg --release
