name: Wasm build

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build wasm
        run: wasm-pack build --target web --out-dir si-web-react/src/si-emu-pkg --release
