name: Wasm NPM Publish

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install wasm-pack
        run: |
          cargo install wasm-pack
          export PATH="$HOME/.cargo/bin:$PATH"

      - name: Build wasm
        run: wasm-pack build --target web --out-name index --out-dir si-emu-pkg --release

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Publish to NPM
        run: |
          cd si-emu-pkg
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
